# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param N the number of samples
#' @param thin the number of between-sample random numbers
#' @return a random sample of size 
#' @examples
#' \dontrun{
#' rnC <- gibbsC(100,10)
#' par(mfrow=c(2,1));
#' plot(rnC[,1],type='l')
#' plot(rnC[,2],type='l')
#' }
#' @export
gibbsC <- function(N, thin) {
    .Call('_StatComp22084_gibbsC', PACKAGE = 'StatComp22084', N, thin)
}

cppgibbs <- function(N, mu1, mu2, sigma1, sigma2, rho) {
    .Call('_StatComp22084_cppgibbs', PACKAGE = 'StatComp22084', N, mu1, mu2, sigma1, sigma2, rho)
}

